export const SOCKET_EVENTS = {
    CREATE_ROOM: 'createRoom',
    CONNECTION: 'connection',
    ROOM_CREATED: 'roomCreated',
    JOIN_ROOM: 'joinRoom',
    JOIN_CALLBACK: 'joinCallback',
    STATUS_CHANGE: 'statusChange',
    ROOM_JOINED: 'roomJoined',
    ROOM_START: 'roomStart',
    ROOM_STARTED: 'roomStarted',
    CANVAS_IMAGE: 'canvasImage',
    GUESS_ATTEMPT: 'guessAttempt',
    GUESS_SUCCEEDED: 'guessSucceeded',
    GUESS_FAILED: 'guessFailed',
}
